version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_go_service
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: admin
      POSTGRES_DB: go_service
      PGDATA: /data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"